### PR TITLE
Add support fo calling read pixels with pixel pack buffer as target

### PR DESCRIPTION
**Pull request by mmatyas**
This adds support for calling ReadPixels with a raw byte offset with the intention of reading into a bound pixel buffer object.

### CODE REVIEW

**Review by jdm — APPROVED** [review]
Please update the Cargo.toml version number as well.

**Comment by mmatyas** [comment]
Ok, updated.

**Comment by nox** [comment]
That method is unsound and can make the GL system write to `buffer_byte_offset as *mut _`, which is not guaranteed to be a valid address (obviously, it's not even a pointer to begin with).

**Comment by jdm** [comment]
https://github.com/servo/sparkle/commit/9de6e1872509847dc124388f28b97cbf71778e0f addresses the unsoundness by making the method unsafe and adding useful documentation.

**Pull request merged**
